services:
  postgres:
    image: postgres:16-alpine
    container_name: sistema2026-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sistema2026
    volumes:
      - postgres_data_sistema2026:/var/lib/postgresql/data

volumes:
  postgres_data_sistema2026:
